sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - docker build -t aurman_docker .
install:
  - python setup.py install
script:
  - python src/unit_tests/test_split_query_helper.py
  - python src/unit_tests/test_parse_pacman_args.py
  - docker run aurman_docker src/docker_tests/install_tests.py
  - docker run aurman_docker src/docker_tests/cache_tests.py
  - docker run aurman_docker src/docker_tests/build_dir_tests.py
  - docker run aurman_docker src/docker_tests/testing_repo_tests.py
  - docker run aurman_docker src/docker_tests/pkgdest_tests.py
  # - docker run aurman_docker src/docker_tests/archive_tests.py
notifications:
  email: false
