sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - docker build -t aurman_docker .
install:
  - python setup.py install
script:
  - python src/unit_tests/test_split_query_helper.py
  - python src/unit_tests/test_parse_pacman_args.py
  - docker run aurman_docker install_tests
  - docker run aurman_docker cache_tests
  - docker run aurman_docker build_dir_tests
  - docker run aurman_docker testing_repo_tests
  - docker run aurman_docker pkgdest_tests
  - docker run aurman_docker archive_tests
notifications:
  email: false
